blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path("list/", ArticleListView.as_view(), name="article_list"),
    path("article_view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("customers/", include("customers.urls", namespace="customers")),
    path("mail_messages/", include("mail_messages.urls", namespace="mail_messages")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

customers/urls.py
from django.urls import path

from customers.views import (
    CustomerListView,
    CustomerCreateView,
    CustomerDetailView,
    CustomerUpdateView,
    CustomerDeleteView,
)

app_name = "customers"

urlpatterns = [
    path("list/", CustomerListView.as_view(), name="customer_list"),
    path("create/", CustomerCreateView.as_view(), name="customer_create"),
    path("view/<int:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("edit/<int:pk>/", CustomerUpdateView.as_view(), name="customer_edit"),
    path("delete/<int:pk>/", CustomerDeleteView.as_view(), name="customer_delete"),
]

mail_messages/urls.py
from django.urls import path

from mail_messages.views import (
    MessageListView,
    MessageCreateView,
    MessageDetailView,
    MessageUpdateView,
    MessageDeleteView,
)

app_name = "mail_messages"

urlpatterns = [
    path("list/", MessageListView.as_view(), name="message_list"),
    path("create/", MessageCreateView.as_view(), name="message_create"),
    path("view/<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path("edit/<int:pk>", MessageUpdateView.as_view(), name="message_edit"),
    path("delete/<int:pk>", MessageDeleteView.as_view(), name="message_delete"),
]

mailing/urls.py
from django.urls import path

from mailing.views import (
    HomeView,
    MailingListView,
    MailingCreateView,
    MailingDetailView,
    MailingUpdateView,
    MailingDeleteView,
    LogListView,
    LogDetailView,
    AccessErrorView,
)

app_name = "mailing"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("list/", MailingListView.as_view(), name="mailing_list"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("view/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("edit/<int:pk>/", MailingUpdateView.as_view(), name="mailing_edit"),
    path("delete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("log_list/", LogListView.as_view(), name="log_list"),
    path("log_view/<int:pk>/", LogDetailView.as_view(), name="log_detail"),
    path("403error/", AccessErrorView.as_view(), name="access_error"),
]

mailing/models.py
from django.db import models

from customers.models import Customer
from mail_messages.models import Message
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Mailing(models.Model):
    #  варианты периодичности рассылки
    ONCE = 'Единоразовая'
    DAILY = 'Раз в день'
    WEEKLY = 'Раз в неделю'
    MONTHLY = 'Раз в месяц'

    PERIOD_CHOICES = (
        (ONCE, 'Единоразовая'),
        (DAILY, 'Раз в день'),
        (WEEKLY, 'Раз в неделю'),
        (MONTHLY, 'Раз в месяц'),
    )
    #  варианты статуса рассылки
    CREATED = 'created'
    STARTED = 'started'
    FINISHED = 'finished'

    STATUS_CHOICES = (
        (CREATED, 'Создана'),
        (STARTED, 'Запущена'),
        (FINISHED, 'Завершена'),
    )

    datetime_start = models.DateTimeField(verbose_name='время начала рассылки')
    datetime_finish = models.DateTimeField(verbose_name='время окончания рассылки')
    period = models.CharField(max_length=25, choices=PERIOD_CHOICES, default=DAILY, verbose_name='периодичность')
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default=CREATED, verbose_name='статус')

    customers = models.ManyToManyField(Customer, verbose_name='Контакты клиентов')
    messages = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение', null=True, blank=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f'{self.datetime_start}-{self.datetime_finish}, {self.period}, {self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class Log(models.Model):
    """Логи рассылки"""
    SUCCESS = 'success'
    FAIL = 'fail'

    STATUSES = (
        (SUCCESS, 'успешно'),
        (FAIL, 'не успешно')
    )
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    clients = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True, verbose_name='контакты клиентов')
    try_time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    try_status = models.CharField(max_length=50, choices=STATUSES, verbose_name='статус попытки')
    server_answer = models.CharField(max_length=250, null=True, blank=True, verbose_name='ответ почтового сервера')

    def __str__(self):
        return f'{self.try_time}: {self.try_status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailing/forms.py
from django import forms
from mailing.models import Mailing
from customers.forms import StyleFormMixin


class MailingForm(StyleFormMixin, forms.ModelForm):
    """Форма для создания/редактирования рассылки"""

    class Meta:
        model = Mailing
        exclude = ('owner',)


class MailingManagerForm(StyleFormMixin, forms.ModelForm):
    """Форма для менеджера для изменения статуса рассылки """

    class Meta:
        model = Mailing
        fields = ('status', )

mailing/views.py
import random

from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from customers.models import Customer
from mailing.models import Mailing, Log

from mailing.forms import MailingForm, MailingManagerForm

from mailing.services import get_cashed_article_list


class OwnerRequiredMixin(DetailView):
    """Миксин проверки прав доступа к объекту"""

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.owner != request.user:
            return redirect('mailing:access_error')
        return super().dispatch(request, *args, **kwargs)


class ManagerRequiredMixin(DetailView):
    """Миксин проверки прав доступа к объекту для менеджеров"""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_manager:
            return redirect('mailing:access_error')
        return super().dispatch(request, *args, **kwargs)


class ManagerOrOwnerRequiredMixin(DetailView):
    """Миксин проверки прав доступа к объекту, доступ только для автора и менеджера"""

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not request.user.is_manager and obj.owner != request.user:
            return redirect('mailing:access_error')
        return super().dispatch(request, *args, **kwargs)


class HomeView(TemplateView):
    """Контроллер просмотра домашней страницы"""
    template_name = "mailing/home.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        article_list = list(get_cashed_article_list())
        if len(article_list) >= 3:
            article_random_list = random.sample(article_list, 3)
            context_data['article_list'] = article_random_list

        context_data['mailing_count'] = Mailing.objects.all().count()
        context_data['mailing_started_count'] = Mailing.objects.filter(status='started').count()
        context_data['mailing_customers_count'] = Customer.objects.all().count()

        return context_data


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form(self, form_class=None):  # отображение только тех контактов, которые созданы пользователем
        form = super().get_form(form_class=None)
        form.fields['customers'].queryset = form.fields['customers'].queryset.filter(owner=self.request.user.id)
        return form

    def form_valid(self, form):  # автоматическое присвоение автора рассылки
        if form.is_valid():
            product = form.save()
            product.owner = self.request.user
            product.save()

        return super().form_valid(form)




class MailingListView(ListView):
    """Контроллер просмотра списка рассылок"""
    model = Mailing
    paginate_by = 9  # количество элементов на одну страницу
    ordering = ['-id']

    def get_queryset(self, *args, **kwargs):  # отображение только тех рассылок, которые созданы пользователем
        queryset = super().get_queryset()
        if not self.request.user.is_manager:  # менеджеру доступны все рассылки
            queryset = queryset.filter(owner=self.request.user.pk)
        return queryset


class MailingDetailView(DetailView):
    """Контроллер просмотра отдельной рассылки"""
    model = Mailing


class MailingUpdateView(UpdateView):
    """Контроллер редактирования рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        if self.request.user.is_manager:
            return MailingManagerForm(**self.get_form_kwargs())

        return super().get_form(form_class)


class MailingDeleteView(DeleteView):
    """Контроллер удаления рассылки"""
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


class LogListView(ListView):
    """Контроллер просмотра логов"""
    model = Log
    paginate_by = 9  # количество элементов на одну страницу

    def dispatch(self, request, *args, **kwargs):  # запрет доступа без авторизации
        if self.request.user.is_anonymous:
            return redirect('mailing:access_error')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):  # отображение логов только тех рассылок, которые созданы пользователем
        context_data = super().get_context_data(**kwargs)
        obj_lst = []
        for log in Log.objects.all():
            if log.mailing.owner == self.request.user or self.request.user.is_manager:  # менеджеру доступны все логи
                obj_lst.append(log)
        obj_lst.reverse()
        context_data['object_list'] = obj_lst
        return context_data


class LogDetailView(DetailView):
    """Контроллер просмотра отдельного лога"""
    model = Log

    def dispatch(self, request, *args, **kwargs):  # доступ к логу только по рассылке, которая создана пользователем
        obj = self.get_object()
        if (obj.mailing.owner != request.user) and (not self.request.user.is_manager):  # менеджеру доступны все логи
            return redirect('mailing:access_error')
        return super().dispatch(request, *args, **kwargs)


class AccessErrorView(TemplateView):
    """Контроллер ошибки доступа"""
    template_name = 'mailing/access_error.html'

mailing/templates/mailing/access_error.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Ошибка доступа</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h5>Вы не имеете доступа к данному объекту</h5>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>mailing_service</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'mailing/includes/inc_main_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">СЕРВИС РАССЫЛОК</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-2">Сервис рассылок</h1>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card shadow-sm">
                <img src="/media/contacts.png" class="card-img-top" alt="Контакты">
                <div class="card-body">
                    <h3 class="card-title">Контакты</h3>
                    <div class="btn-group">
                        {% if user.is_authenticated and not user.is_staff %}
                        <a href="{% url 'customers:customer_list' %}" class="btn btn-block btn-outline-primary">Посмотреть все</a>
                        {% if not user.is_manager %}
                        <a href="{% url 'customers:customer_create' %}" class="btn btn-block btn-outline-primary">Добавить нового</a>
                        {% endif %}
                        {% elif user.is_superuser %}
                        <a href="{% url 'customers:customer_list' %}" class="btn btn-block btn-outline-primary">Посмотреть все</a>
                        <a href="{% url 'customers:customer_create' %}" class="btn btn-block btn-outline-primary">Добавить нового</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm">
                <img src="/media/messages.png" class="card-img-top" alt="Сообщение">
                <div class="card-body">
                    <h3 class="card-title">Сообщение</h3>
                    <div class="btn-group">
                        {% if user.is_authenticated and not user.is_staff %}
                        {% if not user.is_manager %}
                        <a href="{% url 'mail_messages:message_create' %}" class="btn btn-block btn-outline-primary">Добавить новое</a>
                        {% endif %}
                        {% elif user.is_superuser %}
                        <a href="{% url 'mail_messages:message_list' %}" class="btn btn-block btn-outline-primary">Посмотреть все</a>
                        <a href="{% url 'mail_messages:message_create' %}" class="btn btn-block btn-outline-primary">Добавить новое</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm">
                <img src="/media/mailing.png" class="card-img-top" alt="Рассылка">
                <div class="card-body">
                    <h3 class="card-title">Рассылка</h3>
                    <div class="btn-group">
                        {% if user.is_authenticated and not user.is_staff %}
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-block btn-outline-primary">Посмотреть все</a>
                        {% if not user.is_manager %}
                        <a href="{% url 'mailing:mailing_create' %}" class="btn btn-block btn-outline-primary">Добавить новую</a>
                        {% endif %}
                        {% elif user.is_superuser %}
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-block btn-outline-primary">Посмотреть все</a>
                        <a href="{% url 'mailing:mailing_create' %}" class="btn btn-block btn-outline-primary">Добавить новую</a>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="my-5">
        <p class="lead fst-italic display-6 text-center">О нашем сервисе в цифрах</p>
        <div class="row text-center">
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="130" height="130"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title></title>
                    <rect width="100%" height="100%" fill="#83cbea"/>
                    <text x="43%" y="50%" fill="#000" dy=".3em" font-weight="bold" font-size="2em">{{ mailing_count }}</text>
                </svg>
                <h3>Созданных рассылок</h3>
            </div>
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="130" height="130"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title></title>
                    <rect width="100%" height="100%" fill="#83cbea"/>
                    <text x="43%" y="50%" fill="#000" dy=".3em" font-weight="bold" font-size="2em">{{ mailing_started_count }}</text>
                </svg>
                <h3>Рассылок запущено</h3>
            </div>
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="130" height="130"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title></title>
                    <rect width="100%" height="100%" fill="#83cbea"/>
                    <text x="43%" y="50%" fill="#000" dy=".3em" font-weight="bold" font-size="2em">{{ mailing_clients_count }}</text>
                </svg>
                <h3>Уникальных клиентов</h3>
            </div>
        </div>
    </div>

    <div class="my-5">
        <p class="lead fst-italic display-6 text-center">Интересно знать</p>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in article_list %}
            <div class="col">
                <div class="card shadow-sm py-3">
                    <p class="text-center fw-bold">{{ object.title }}</p>
                    <div class="card-body">
                        <p class="card-text">{{ object.body|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'blog:article_detail' object.pk %}" class="btn btn-outline-warning">Подробнее</a>
                            <small class="text-muted">{{ object.date }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {% include 'mailing/includes/inc_under_menu.html' %}
</div>
{% endblock %}

mailing/templates/mailing/log_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<h1>Детали рассылки</h1>

<p>Тема: {{ object.mailing.message.subject }}</p>
<p>Текст: {{ object.mailing.message.text }}</p>
<p>Время начала: {{ object.mailing.datetime_start }}</p>
<p>Время окончания: {{ object.mailing.datetime_finish }}</p>
<p>Периодичность: {{ object.mailing.get_period_display }}</p>
<p>Статус: {{ object.mailing.get_status_display }}</p>

{% if object.mailing.customers.all %}
<p>Кому:
    {% for client in object.mailing.customers.all %}
    {{ customers.email }}{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
{% else %}
<p>Кому: -</p>
{% endif %}

<p>Попытка: {{ object.try_time }}</p>
<p>Статус попытки: {{ object.get_try_status_display }}</p>
<p>Ответ сервера: {{ object.server_answer }}</p>
{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статистика</h1>
</div>

<div class="container">
   <br>
   <table class="table">
   <thead>
       <tr>
       <th scope="col">id</th>
       <th scope="col">Рассылка</th>
       <th scope="col">Контакт</th>
       <th scope="col">Статус</th>
       </tr>
   </thead>
   {% for object in object_list %}
   <tbody>
      <tr>
      <th scope="row">{{ object.pk }}</th>
      <td>{{ object.mailing.message.subject }}</td>
      <td>{{ object.customers.email }}</td>
      <td>
      {% for client in object.mailing.customers.all %}
      {{ customers.email }}{% if not forloop.last %}, {% endif %}
      {% endfor %}
    </td>
      <td>{{ object.try_status }}</td>
      <td>
          <a href="{% url 'mailing:log_detail' object.pk %}" class="btn btn-outline-warning">Подробнее</a>
      </td>
      </tr>
   </tbody>
   {% endfor %}
   </table>
</div>

<div id="pages" align="center">
   {% if page_obj.has_previous %}
       <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
   {% endif %}
   <span class="current">
       Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
   </span>
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
   {% endif %}
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-danger text-white">
                    <h4 class="card-title mb-0">Удалить рассылку</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить рассылку "{{ object }}"?</p>
                        <div class="text-right">
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">

                    <h4 class="card-title mb-0">Рассылка</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ object.message }}</h5>
                    <p>Время начала: {{ object.datetime_start }}</p>
                    <p>Время окончания: {{ object.datetime_finish }}</p>
                    <p>Периодичность: {{ object.get_period_display }}</p>
                    <p>Статус: {{ object.get_status_display }}</p>
                    <div class="text-right">
                        <a href="{% url 'mailing:mailing_edit' object.pk %}" class="btn btn-sm btn-outline-primary">Изменить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="card-title mb-0">
                        {% if object %}Редактировать рассылку: {{ object.message }}{% else %}Добавить рассылку{% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success">
                                {% if object %}Сохранить{% else %}Создать{% endif %}
                            </button>
                            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="d-flex justify-content-between mb-3">
        <h1 class="display-4">Рассылки</h1>
        <a href="{% url 'mailing:mailing_create' %}" class="btn btn-primary">Добавить новую</a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Сообщение</th>
                    <th scope="col">Периодичность</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.pk }}</th>
                    <td>{{ object.messages }}</td>
                    <td>{{ object.get_period_display }}</td>
                    <td>{{ object.get_status_display }}</td>
                    <td>
                        <a href="{% url 'mailing:mailing_detail' object.pk %}" class="btn btn-sm btn-outline-primary">Подробнее</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-center mt-3">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary mr-2">Предыдущая</a>
        {% endif %}
        <span class="pagination-info">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary ml-2">Следующая</a>
        {% endif %}
    </div>
</div>
{% endblock %}