blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path("list/", ArticleListView.as_view(), name="article_list"),
    path("article_view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("customers/", include("customers.urls", namespace="customers")),
    path("mail_messages/", include("mail_messages.urls", namespace="mail_messages")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mail_messages/urls.py
from django.urls import path

from mail_messages.views import (
    MessageListView,
    MessageCreateView,
    MessageDetailView,
    MessageUpdateView,
    MessageDeleteView,
)

app_name = "mail_messages"

urlpatterns = [
    path("list/", MessageListView.as_view(), name="message_list"),
    path("create/", MessageCreateView.as_view(), name="message_create"),
    path("view/<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path("edit/<int:pk>", MessageUpdateView.as_view(), name="message_edit"),
    path("delete/<int:pk>", MessageDeleteView.as_view(), name="message_delete"),
]

mail_messages/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Message(models.Model):
    message_subject = models.CharField(max_length=100, verbose_name="Тема письма")
    text = models.TextField(verbose_name="Текст письма")

    owner = models.ForeignKey("users.User", on_delete=models.CASCADE, **NULLABLE, related_name='messages')

    def __str__(self):
        return self.message_subject

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"

mail_messages/forms.py
from django import forms
from mail_messages.models import Message
from customers.forms import StyleFormMixin


class MessageForm(StyleFormMixin, forms.ModelForm):
    """Форма для создания/редактирования сообщения"""

    class Meta:
        model = Message
        exclude = ("owner",)

mail_messages/views.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from mail_messages.forms import MessageForm
from mail_messages.models import Message
from mailing.views import ManagerOrOwnerRequiredMixin, OwnerRequiredMixin


class MessageListView(ListView):
    """Контроллер просмотра списка сообщений для рассылки"""

    model = Message
    paginate_by = 6
    ordering = ["-id"]

    def dispatch(self, request, *args, **kwargs):  # запрет доступа без авторизации
        if self.request.user.is_anonymous:
            return redirect("mailing:access_error")
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(
        self, *args, **kwargs
    ):  # # отображение только тех сообщений, которые созданы пользователем
        queryset = super().get_queryset()
        if not self.request.user.is_manager:  # менеджеру доступны все сообщения
            queryset = queryset.filter(owner=self.request.user.pk)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания сообщения для рассылки"""

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mail_messages:message_list")

    def form_valid(self, form):
        if form.is_valid():
            product = form.save()
            product.owner = self.request.user
            product.save()

        return super().form_valid(form)


class MessageDetailView(ManagerOrOwnerRequiredMixin, DetailView):
    """Контроллер просмотра отдельного сообщения для рассылки"""

    model = Message


class MessageUpdateView(OwnerRequiredMixin, UpdateView):
    """Контроллер редактирования сообщения для рассылки"""

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mail_messages:message_list")


class MessageDeleteView(OwnerRequiredMixin, DeleteView):
    """Контроллер удаления сообщения для рассылки"""

    model = Message
    success_url = reverse_lazy("mail_messages:message_list")

mail_messages/templates/mail_messages/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удалить сообщение</h1>
</div>

<div class="container">
    <div class="col-12">
    <div class="row text-start">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение "{{ object }}"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mail_messages:message_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

mail_messages/templates/mail_messages/message_detail.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сообщение</h1>
</div>

<div class="container">
    <div class="col-12">
    <div class="row text-start">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object.subject }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.text }}
                    </p>
                     <div class="btn-group">
                         <a href="{% url 'mail_messages:message_edit' object.pk %}"
                             class="btn btn-sm btn-outline-secondary">Изменить</a>
                         <a href="{% url 'mail_messages:message_delete' object.pk %}"
                             class="btn btn-sm btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

mail_messages/templates/mail_messages/message_form.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if object %}
        Редактировать
        {% else %}
        Добавить сообщение
        {% endif %}
    </h1>
</div>

<div class="container">
    <div class="col-12">
    <div class="row text-start">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                        <a href="{% url 'mail_messages:message_list' %}" class="btn btn-outline-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

mail_messages/templates/mail_messages/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сообщения</h1>
</div>

<div class="container">
    {% if not user.is_manager %}
    <div class="btn-group">
        <a href="{% url 'mail_messages:message_create' %}"
           class="btn btn-block btn-outline-primary">Добавить новое</a>
    </div>
    {% endif %}
</div>

<div class="container">
    <br>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Тема</th>
            <th scope="col">Текст</th>
            <th scope="col">Детали</th>
        </tr>
        </thead>
        {% for object in object_list %}
        <tbody>
        <tr>
            <th scope="row">{{ object.pk}}</th>
            <td>{{ object.subject}}</td>
            <td>{{ object.text|truncatechars:100}}</td>
            <td>
                <a href="{% url 'mail_messages:message_detail' object.pk %}"
                   class="btn btn-outline-warning">Подробнее</a>
            </td>
        </tr>
        </tbody>
        {% endfor %}
    </table>


    <div id="pages" align="center">
        {% if page_obj.has_previous %}
        <a href="?page={{ page.obj.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <span class="current">
       Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
   </span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
        {% endif %}
    </div>
</div>

{% endblock %}