blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path("list/", ArticleListView.as_view(), name="article_list"),
    path("article_view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("customers/", include("customers.urls", namespace="customers")),
    path("mail_messages/", include("mail_messages.urls", namespace="mail_messages")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

customers/urls.py
from django.urls import path

from customers.views import (
    CustomerListView,
    CustomerCreateView,
    CustomerDetailView,
    CustomerUpdateView,
    CustomerDeleteView,
)

app_name = "customers"

urlpatterns = [
    path("list/", CustomerListView.as_view(), name="customer_list"),
    path("create/", CustomerCreateView.as_view(), name="customer_create"),
    path("view/<int:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("edit/<int:pk>/", CustomerUpdateView.as_view(), name="customer_edit"),
    path("delete/<int:pk>/", CustomerDeleteView.as_view(), name="customer_delete"),
]

customers/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Customer(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    email = models.EmailField(unique=True, verbose_name="e-mail")
    description = models.TextField(verbose_name="описание", **NULLABLE)

    company_name = models.CharField(
        max_length=50, verbose_name="имя компании", **NULLABLE
    )

    owner = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, **NULLABLE, verbose_name="автор"
    )

    def __str__(self):
        return f"{self.first_name} - {self.email}"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"

customers/forms.py
from django import forms
from customers.models import Customer


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class CustomerForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Customer
        exclude = ("owner",)

customers/views.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect

from customers.forms import CustomerForm
from customers.models import Customer
from mailing.views import ManagerOrOwnerRequiredMixin, OwnerRequiredMixin


class CustomerListView(ListView):
    """Контроллер создания клиента сервиса"""

    model = Customer
    paginate_by = 15
    ordering = ["-id"]

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return redirect("mailing:access_error")
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        if not self.request.user.is_manager:
            queryset = queryset.filter(owner=self.request.user.pk)
        return queryset


class CustomerCreateView(LoginRequiredMixin, CreateView):
    """Контроллер просмотра списка клиентов сервиса"""

    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy("customers:customer_list")

    def form_valid(self, form):
        if form.is_valid():
            contact = form.save()
            contact.owner = self.request.user
            contact.save()

        return super().form_valid(form)


class CustomerDetailView(ManagerOrOwnerRequiredMixin, DetailView):
    """Контроллер просмотра отдельного клиента сервиса"""

    model = Customer


class CustomerUpdateView(OwnerRequiredMixin, UpdateView):
    """Контроллер редактирования клиента сервиса"""

    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy("customers:customer_list")


class CustomerDeleteView(OwnerRequiredMixin, DeleteView):
    """Контроллер удаления клиента сервиса"""

    model = Customer
    success_url = reverse_lazy("customers:customer_list")

customers/templates/customers/customer_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удалить клиента</h1>
</div>

<div class="container">
    <div class="col-12">
    <div class="row text-start">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{ object.first_name }}"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'customers:customer_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

customers/templates/customers/customer_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="card-title mb-0">Клиент</h4>
                </div>
                <div class="card-body">

                    <h5 class="card-title">{{ object.email }}</h5>
                    <p>{{ object.first_name }}</p>
                    <p>{{ object.company_name }}</p>
                    <p>{{ object.description }}</p>
                    <div class="text-right">
                        <a href="{% url 'customers:customer_edit' object.pk %}" class="btn btn-sm btn-outline-primary">Изменить</a>
                        <a href="{% url 'customers:customer_delete' object.pk %}" class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

customers/templates/customers/customer_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="card-title mb-0">
                        {% if object %}Редактировать контакт{% else %}Добавить контакт{% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success">
                                {% if object %}Сохранить{% else %}Создать{% endif %}
                            </button>
                            <a href="{% url 'customers:customer_list' %}" class="btn btn-warning">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

customers/templates/customers/customer_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="d-flex justify-content-between mb-3">
        <h1 class="display-4">Клиенты</h1>
        <a href="{% url 'customers:customer_create' %}" class="btn btn-primary">Добавить нового</a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Название компании</th>
                    <th scope="col">Email</th>
                    <th scope="col">Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.pk }}</th>
                    <td>{{ object.first_name }}</td>
                    <td>{{ object.company_name }}</td>
                    <td>{{ object.email }}</td>
                    <td>
                        <a href="{% url 'customers:customer_detail' object.pk %}" class="btn btn-sm btn-outline-primary">Подробнее</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-center mt-3">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary mr-2">Предыдущая</a>
        {% endif %}
        <span class="pagination-info">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary ml-2">Следующая</a>
        {% endif %}
    </div>
</div>
{% endblock %}