blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path("list/", ArticleListView.as_view(), name="article_list"),
    path("article_view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("customers/", include("customers.urls", namespace="customers")),
    path("mail_messages/", include("mail_messages.urls", namespace="mail_messages")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mailing/urls.py
from django.urls import path

from mailing.views import (
    HomeView,
    MailingListView,
    MailingCreateView,
    MailingDetailView,
    MailingUpdateView,
    MailingDeleteView,
    LogListView,
    LogDetailView,
    AccessErrorView,
)

app_name = "mailing"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("list/", MailingListView.as_view(), name="mailing_list"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("view/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("edit/<int:pk>/", MailingUpdateView.as_view(), name="mailing_edit"),
    path("delete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("log_list/", LogListView.as_view(), name="log_list"),
    path("log_view/<int:pk>/", LogDetailView.as_view(), name="log_detail"),
    path("403error/", AccessErrorView.as_view(), name="access_error"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    verify,
    check_email,
    PasswordResetView,
    UserListView,
    UserUpdateView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("verify/<int:id_user>", verify, name="verify"),
    path("check_email", check_email, name="check_email"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("list/", UserListView.as_view(), name="user_list"),
    path("edit/<int:pk>/", UserUpdateView.as_view(), name="user_edit"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager

class User(AbstractUser):
    """Пользователь"""

    avatar = models.ImageField(
        upload_to="users/avatars/", blank=True, null=True, verbose_name="аватар"
    )
    phone = models.CharField(
        max_length=30, blank=True, null=True, verbose_name="телефон"
    )

    is_manager = models.BooleanField(
        default=False, blank=True, null=True, verbose_name="менеджер"
    )  # права менеджера

    username = None
    email = models.EmailField(unique=True, verbose_name="почта")

    token = models.CharField(
        max_length=100, verbose_name="Токен", blank=True, null=True
    )

    id = models.IntegerField(
        primary_key=True, default=3, editable=False, verbose_name="id_пользователя"
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class RegisterCreationForm(UserCreationForm):
    """
    Форма регистрации
    """

    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(UserChangeForm):
    """
    Форма профиля
    """

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()


class PasswordResetForm(forms.Form):
    """
    Форма для сброса пароля
    """

    email = forms.EmailField(label="Email")


class UserStatusForm(UserChangeForm):
    """Форма для управления статусом пользователя"""

    class Meta:
        model = User
        fields = ("is_active",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()

users/views.py
import random
import string

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, FormView, ListView

from config import settings
from config.settings import DEFAULT_FROM_EMAIL
from mailing.views import ManagerRequiredMixin
from users.forms import (
    RegisterCreationForm,
    UserProfileForm,
    PasswordResetForm,
    UserStatusForm,
)
from users.models import User


class RegisterView(CreateView):
    """Контроллер создания пользователя"""

    model = User
    form_class = RegisterCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:check_email")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        send_mail(
            "Подтвердите свою почту",
            f"Ваша учетная запись подтверждена!\nПерейдите по ссылке - http://127.0.0.1:8000/users/verify/{user.pk}",
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False,
        )
        return super().form_valid(form)


def verify(request, id_user):
    user = get_object_or_404(User, id=id_user)
    if user.is_active is False:
        user.is_active = True
        user.save()
        return HttpResponseRedirect(reverse_lazy("users:login"))
    return HttpResponseRedirect(reverse_lazy("users:register"))


def check_email(request):
    return render(request, "users/check_email.html")


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("mailing:home")

    def get_object(self, queryset=None):
        return self.request.user


class PasswordResetView(FormView):
    model = User
    form_class = PasswordResetForm
    template_name = "users/password_reset_form.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email_form = form.cleaned_data["email"]
        try:
            user = User.objects.get(email=email_form)
        except User.DoesNotExist:
            return render(
                self.request,
                self.template_name,
                {"form": form, "error": "Пользователь с таким email-ом не найден"},
            )
        new_pass = "".join(random.choices(string.ascii_letters + string.digits, k=8))
        user.set_password(new_pass)
        user.save()

        send_mail(
            subject="Новый пароль",
            message=f"Ваш новый пароль: {new_pass}",
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=[user.emails],
            fail_silently=False,
        )

        return super().form_valid(form)


class UserUpdateView(ManagerRequiredMixin, UpdateView):
    """Контроллер редактирования пользователя"""

    model = User
    form_class = UserStatusForm
    success_url = reverse_lazy("users:user_list")


class UserListView(ListView):
    model = User
    paginate_by = 9
    ordering = ["-id"]

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return redirect("mailing:access_error")
        elif not self.request.user.is_manager:
            return redirect("mailing:access_error")
        return super().dispatch(request, *args, **kwargs)

users/templates/users/check_email.html
{% extends 'mailing/base.html' %}

{% block content %}


<div class="col-12 m-3">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Подтверждение электронной почты</h3>
            <div class="card-body">
                <p></p>
                <p>
                    Для продолжения регистрации пройдите по ссылке в письме электронной почты указанной при регистрации!
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Войти в свой аккаунт</h1>
</div>

<div class="container">
    <div class="col-12 d-flex justify-content-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-success">
                                Войти
                        </button>
                        <a href="{% url 'mailing:home' %}" class="btn btn-outline-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block content %}


<div class="row col-6">
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Запрос на восстановление пароля на сайте</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Адрес электронной почты</label>
                    <input type="email" class="form-control" name="email" id="exampleFormControlInput1"
                           placeholder="name@example.com">
                    <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Регистрация</h1>
</div>

<div class="container">
    <div class="col-12 d-flex justify-content-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-success">
                                Регистрация
                        </button>
                        <a href="{% url 'mailing:home' %}" class="btn btn-outline-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12 m-3">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Профиль</h3>
                        <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}

                            <p></p>
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пользователи</h1>
</div>

<div class="container">

   <br><br><table class="table">
   <thead>
       <tr>
       <th scope="col">id</th>
       <th scope="col">Email</th>
       <th scope="col">Детали</th>
       </tr>
   </thead>
   {% for object in object_list %}
   {% if not object.is_superuser and not object.is_manager%}
   <tbody>
      <tr>
      <th scope="row">{{ object.pk}}</th>
      <td>{{ object.email}}</td>
      <td>
          <a href="{% url 'users:user_edit' object.pk %}" class="btn btn-outline-warning">Редактировать</a>
      </td>
      </tr>
   </tbody>
   {% endif %}
   {% endfor %}
   </table>



<div id="pages" align="center">
   {% if page_obj.has_previous %}
       <a href="?page={{ page.obj.previous_page_number }}">Предыдущая</a>
   {% endif %}
   <span class="current">
       Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
   </span>
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
   {% endif %}
</div>
</div>

{% endblock %}